#!/bin/sh /etc/rc.common
#
# Copyright (C) 2016 Jian Chang <aa65535@live.com>
#
# This is free software, licensed under the GNU General Public License v3.
# See /LICENSE for more information.
#

START=90
STOP=15

NAME=shadowsocks
EXTRA_COMMANDS=rules
CONFIG_FILE=/var/etc/$NAME.json

uci_get_by_name() {
	local ret=$(uci get $NAME.$1.$2 2>/dev/null)
	echo ${ret:=$3}
}

uci_get_by_type() {
	local ret=$(uci get $NAME.@$1[0].$2 2>/dev/null)
	echo ${ret:=$3}
}

get_arg_ota() {
	case "$(uci_get_by_name $1 auth)" in
		1|on|true|yes|enabled) echo "-A";;
	esac
}

gen_config_file() {
	cat <<-EOF >$CONFIG_FILE
		{
		    "server": "$(uci_get_by_name $1 server)",
		    "server_port": $(uci_get_by_name $1 server_port),
		    "local_address": "0.0.0.0",
		    "password": "$(uci_get_by_name $1 password)",
		    "timeout": $(uci_get_by_name $1 timeout 60),
		    "method": "$(uci_get_by_name $1 encrypt_method)"
		}
EOF
}

gen_lan_hosts() {
	case "$(uci_get_by_name $1 enable)" in
		1|on|true|yes|enabled)
			echo "$(uci_get_by_name $1 type),$(uci_get_by_name $1 host)";;
	esac
}

get_server_ips() {
	echo $(uci_get_by_name $1 server)
}

start_rules() {
	local arg_udp
	local main_server=$(uci_get_by_type transparent_proxy main_server)
	local udp_relay_server=$(uci_get_by_type transparent_proxy udp_relay_server)
	[ "$udp_relay_server" = "same" ] && udp_relay_server=$main_server
	if [ "$udp_relay_server" = "$main_server" ]; then
		arg_udp="-u"
	elif [ -n "$udp_relay_server" -a "$udp_relay_server" != "nil" ]; then
		arg_udp="-U"
	fi
	config_load $NAME
	local server_ips=$(echo $(config_foreach get_server_ips servers))
	local local_port=$(uci_get_by_type transparent_proxy local_port 1234)
	/usr/bin/ss-rules \
		-s "$server_ips" \
		-l "$local_port" \
		-S "$server_ips" \
		-L "$local_port" \
		-i "$(uci_get_by_type access_control wan_bp_list)" \
		-b "$(uci_get_by_type access_control wan_bp_ips)" \
		-w "$(uci_get_by_type access_control wan_fw_ips)" \
		-I "$(uci_get_by_type access_control lan_ifaces)" \
		-d "$(uci_get_by_type access_control lan_target)" \
		-a "$(echo $(config_foreach gen_lan_hosts lan_hosts))" \
		-e "$(uci_get_by_type access_control ipt_ext)" \
		-o $arg_udp
		local ret=$?
		[ "$ret" = 0 ] || /usr/bin/ss-rules -f
	return $ret
}

rules() {
	if [ -z "$(pidof ss-redir 2>/dev/null)" ]; then
		logger -st $NAME -p3 "ss-redir not running."
		return 1
	fi
	start_rules
}

start_redir() {
	gen_config_file $1
	ss-redir -c $CONFIG_FILE $2 $(get_arg_ota $1) \
		-l $(uci_get_by_type transparent_proxy local_port 1234) \
		-f /var/run/ss-redir$3.pid
}

ss_redir() {
	if !(command -v ss-redir >/dev/null 2>&1); then
		return 1
	fi
	local main_server=$(uci_get_by_type transparent_proxy main_server)
	[ -z "$main_server" -o "$main_server" = "nil" ] && return 1
	local udp_relay_server=$(uci_get_by_type transparent_proxy udp_relay_server)
	[ "$udp_relay_server" = "same" ] && udp_relay_server=$main_server
	if [ "$udp_relay_server" = "$main_server" ]; then
		start_redir $main_server -u
	elif [ -n "$udp_relay_server" -a "$udp_relay_server" != "nil" ]; then
		start_redir $main_server
		start_redir $udp_relay_server -U -udp
	else
		start_redir $main_server
	fi
}

start_local() {
	gen_config_file $1
	ss-local -c $CONFIG_FILE -u $(get_arg_ota $1) \
		-l $(uci_get_by_type socks5_proxy local_port 1080) \
		-f /var/run/ss-local.pid
}

ss_local() {
	if !(command -v ss-local >/dev/null 2>&1); then
		return 0
	fi
	local server=$(uci_get_by_type socks5_proxy server)
	[ -z "$server" -o "$server" = "nil" ] || start_local $server
}

start_tunnel() {
	gen_config_file $1
	ss-tunnel -c $CONFIG_FILE -u $(get_arg_ota $1) \
		-l $(uci_get_by_type port_forward local_port 5300) \
		-L $(uci_get_by_type port_forward destination 8.8.4.4:53) \
		-f /var/run/ss-tunnel.pid
}

ss_tunnel() {
	if !(command -v ss-tunnel >/dev/null 2>&1); then
		return 0
	fi
	local server=$(uci_get_by_type port_forward server)
	[ -z "$server" -o "$server" = "nil" ] || start_tunnel $server
}

start() {
	mkdir -p /var/run /var/etc
	ss_redir && rules
	ss_local
	ss_tunnel
	rm -f $CONFIG_FILE
}

kill_pid() {
	while [ -n "$1" ]; do
		local pid=$(cat $1 2>/dev/null)
		rm -f $1
		[ -n "$pid" -a -d "/proc/$pid" ] && kill -9 $pid
		shift
	done
}

stop() {
	/usr/bin/ss-rules -f
	kill_pid /var/run/ss-redir.pid \
		/var/run/ss-redir-udp.pid \
		/var/run/ss-local.pid \
		/var/run/ss-tunnel.pid
}
